server:
  port: 9000

spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
  application:
    name: demo

  datasource:
    platform: mysql
    url: jdbc:mysql://localhost:3306/umc?serverTimezone=Asia/Seoul # 변경해주세요
    username:  root
    password:  '0000'
    driver-class-name: com.mysql.cj.jdbc.Driver # mysql 8버전
    # driver-class-name: com.mysql.jdbc.Driver # mysql 5버전